tap "dart-lang/dart"
tap "droidsonroids/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "cocoapods"
brew "cowsay"
brew "fortune"
brew "python@3.10", link: false
brew "scrcpy"
brew "thefuck"
brew "droidsonroids/tools/dor"
cask "rectangle"
cask "tunnelblick"
